training_csv_file: '/homedir06/thtran/research/PAR2023/raw_data/training_set.csv'
testing_csv_file: '/homedir06/thtran/research/PAR2023/raw_data/validation_set.csv'
batch_size: 32
num_epochs: 100
learning_rate: 0.0001
output_model: './Training_Models_NonMinus1'
